name: "dragee-scan-action"
description: "A Github action to scan code with Dragee.io"
author: "dragee-io"

inputs:
  asserter:
    description: "The asserter to use <org>/<asserter>"
    required: false
  from:
    description: "The path to scan"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true

permissions:
  id-token: write
  contents: read

runs:
  using: "composite"
  steps:
    - name: Get OIDC Token
      id: oidc
      uses: actions/github-script@v7
      with:
        script: |
          const token = await core.getIDToken("my-backend");
          core.setOutput("token", token);

    - name: Dagger call run-scan
      uses: dagger/dagger-for-github@v8.2.0
      with:
        module: ${{ github.action_path }}
        call: >-
          run-pipeline
          --from "${{ inputs.from }}"
          --asserter "${{ inputs.asserter }}"
          --grapher
          --github-token env:GITHUB_TOKEN
          --oidc-token env:OIDC_TOKEN
          --backend-url https://api.dragee.io
          --source ${{ github.workspace }}
        version: latest
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OIDC_TOKEN: ${{ steps.oidc.outputs.token }}