name: "dragee-scan-action"
description: "A Github action to scan code with Dragee.io"
author: "dragee-io"

inputs:
  asserter:
    description: "The asserter to use <org>/<asserter>"
    required: false
  from:
    description: "The path to scan"
    required: true

runs:
  using: "composite"
  steps:
    - name: Dagger call run-scan
      uses: dagger/dagger-for-github@v8.2.0
      with:
        module: .
        call: >-
          run-scan
          --from .
          --asserter "${{ inputs.asserter }}"
          --grapher
          --github-token env:GITHUB_TOKEN
          --dragee-token env:DRAGEE_TOKEN
        version: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAGEE_TOKEN: ${{ secrets.DRAGEE_TOKEN }}
