name: "fixentropy-scan-action"
description: "A Github action to scan code with fixentropy.io"
author: "fixentropy-io"

branding:
  icon: 'activity'
  color: 'purple'

inputs:
  asserter:
    description: "The asserter to use <org>/<asserter>"
    required: false
  from:
    description: "The path to scan"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  backend-url:
    description: "The Fixentropy backend URL"
    required: false
    default: "https://app.fixentropy.io/api"


runs:
  using: "composite"
  steps:
    - name: Get OIDC Token
      id: oidc
      uses: actions/github-script@v7
      with:
        script: |
          const token = await core.getIDToken("fixentropy");
          core.setOutput("token", token);

    - name: Dagger call run-scan
      shell: bash
      run: |
        echo "GitHub Token: ${{ inputs.github-token }}"