name: Try Action

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Maven
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: Build with Maven
        run: mvn clean install

      - name: Dragee Scan
#        uses: dragee-io/dragee-scan-action@v1
        uses: "./.github/actions/dragee-scan"
        with:
          from: '/target/dragee/'
          dragee-token: ${{ secrets.DRAGEE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
